### PR TITLE
Added watch to service if config file present.

### PR DESCRIPTION
**Pull request by vladvasiliu**
I have modified the service states so that the beat services are restarted when there's a configuration file change.

### CODE REVIEW

**Comment by psmiraglia** [comment]
Thanks, It sounds good! I'll merge it in the next days.

**Comment by psmiraglia** [comment]
Hi @vladvasiliu, I reviewed your PR and my code. Sorry but seems that your PR implements a feature that is already available under devel branch (see service.sls file). Could you check it please?

**Comment by vladvasiliu** [comment]
Hi, I'll have a look this weekend.

**Comment by psmiraglia** [comment]
Ok. FYI, I merged (and tagged to 0.0.3) the devel features in master.

**Comment by vladvasiliu** [comment]
I had a look over the changes and they seem to do what I wanted. I'll close the PR.

**Pull request closed without merging**
